# Generated by Django 2.0.4 on 2018-05-29 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres_voiture',
            fields=[
                ('param_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_modele', models.CharField(max_length=45, null=True)),
                ('parametre_1', models.FloatField(default=0)),
                ('parametre_2', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('secret', models.CharField(default='DRQIPOLCEBV5VPZK', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_loue_voiture',
            fields=[
                ('ulv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45, null=True)),
                ('date_transaction', models.DateTimeField(auto_now=True)),
                ('consommation', models.FloatField(default=0)),
                ('titre_conso', models.CharField(max_length=45, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_set', to='restApi.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=9, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('parametres_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cars', to='restApi.Parametres_voiture')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_set', to='restApi.Utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_set', to='restApi.Voiture'),
        ),
    ]
