# Generated by Django 2.0.2 on 2018-04-09 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres_voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre_1', models.FloatField(default=0)),
                ('parametre_2', models.FloatField(default=0)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_loue_voiture',
            fields=[
                ('ulv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_transaction', models.DateTimeField(auto_now=True)),
                ('consommation', models.FloatField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_set', to='restApi.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=7, null=True)),
                ('nom_modele', models.CharField(blank=True, max_length=45, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_set', to='restApi.Utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_set', to='restApi.Voiture'),
        ),
        migrations.AddField(
            model_name='parametres_voiture',
            name='voiture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApi.Voiture'),
        ),
    ]
