# Generated by Django 2.0.2 on 2018-03-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses_utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depenses_util', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
                ('voiture_utilisee', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametres_voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre_1', models.FloatField()),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('depenses_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restApi.Depenses_utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_loue_voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_location', models.DateTimeField(auto_now_add=True)),
                ('date_fin_location', models.DateTimeField(auto_now=True)),
                ('consommation_instantanee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(blank=True, max_length=45, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('parametres_voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restApi.Parametres_voiture')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Voiture'),
        ),
    ]
