# Generated by Django 2.0.2 on 2018-03-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='consommation',
            field=models.FloatField(default=0),
        ),
    ]
