# Generated by Django 2.0.2 on 2018-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='matricule',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
