# Generated by Django 2.0.4 on 2018-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur_loue_voiture',
            name='titre_conso',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
