# Generated by Django 2.0.2 on 2018-03-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='depenses_utilisateur',
            name='voiture_utilisee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restApi.Voiture'),
        ),
    ]
