# Generated by Django 2.0.4 on 2018-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_utilisateur_loue_voiture_titre_conso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='matricule',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
