# Generated by Django 2.0.2 on 2018-03-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20180303_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses_utilisateur',
            name='voiture_utilisee',
        ),
        migrations.RenameField(
            model_name='utilisateur_loue_voiture',
            old_name='consommation_instantanee',
            new_name='consommation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='depenses_utilisateur',
        ),
        migrations.AddField(
            model_name='parametres_voiture',
            name='parametre_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parametres_voiture',
            name='parametre_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='parametres_voiture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restApi.Parametres_voiture'),
        ),
        migrations.DeleteModel(
            name='Depenses_utilisateur',
        ),
    ]
