# Generated by Django 2.0.4 on 2018-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20180416_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.AddField(
            model_name='utilisateur_loue_voiture',
            name='nom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
