# Generated by Django 2.0.2 on 2018-03-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20180309_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='restApi.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='restApi.Voiture'),
        ),
        migrations.AlterUniqueTogether(
            name='utilisateur_loue_voiture',
            unique_together={('utilisateur', 'voiture')},
        ),
    ]
