# Generated by Django 2.0.2 on 2018-03-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_auto_20180303_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='parametres_voiture',
        ),
        migrations.AddField(
            model_name='parametres_voiture',
            name='parametres_voiture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restApi.Voiture'),
        ),
    ]
