# Generated by Django 2.0.4 on 2018-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_auto_20180526_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
