# Generated by Django 2.0.4 on 2018-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_auto_20180504_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='nom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
