# Generated by Django 2.0.2 on 2018-03-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_auto_20180310_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Voiture'),
        ),
    ]
