# Generated by Django 2.0.2 on 2018-03-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_auto_20180303_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametres_voiture',
            old_name='parametres_voiture',
            new_name='voiture',
        ),
    ]
