# Generated by Django 2.0.4 on 2018-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='secret',
            field=models.CharField(default='2DFPGENP2J7H4IOF', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
