# Generated by Django 2.0.2 on 2018-03-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_auto_20180310_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_set', to='restApi.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_loue_voiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_set', to='restApi.Voiture'),
        ),
    ]
